export const cardDeckService = {
    cardDeck
}

function cardDeck(){
    const cards = [
        { cardName: '1', cardColor: ['green'], isSpecial: false },
        { cardName: '+2', cardColor: ['green'], isSpecial: true },
        { cardName: '3', cardColor: ['green'], isSpecial: false },
        { cardName: '4', cardColor: ['green'], isSpecial: false },
        { cardName: '5', cardColor: ['green'], isSpecial: false },
        { cardName: '6', cardColor: ['green'], isSpecial: false },
        { cardName: '7', cardColor: ['green'], isSpecial: false },
        { cardName: '8', cardColor: ['green'], isSpecial: false },
        { cardName: '9', cardColor: ['green'], isSpecial: false },
        { cardName: '1', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2', cardColor: ['yellow'], isSpecial: true },
        { cardName: '3', cardColor: ['yellow'], isSpecial: false },
        { cardName: '4', cardColor: ['yellow'], isSpecial: false },
        { cardName: '5', cardColor: ['yellow'], isSpecial: false },
        { cardName: '6', cardColor: ['yellow'], isSpecial: false },
        { cardName: '7', cardColor: ['yellow'], isSpecial: false },
        { cardName: '8', cardColor: ['yellow'], isSpecial: false },
        { cardName: '9', cardColor: ['yellow'], isSpecial: false },
        { cardName: '1', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2', cardColor: ['red'], isSpecial: true },
        { cardName: '3', cardColor: ['red'], isSpecial: false },
        { cardName: '4', cardColor: ['red'], isSpecial: false },
        { cardName: '5', cardColor: ['red'], isSpecial: false },
        { cardName: '6', cardColor: ['red'], isSpecial: false },
        { cardName: '7', cardColor: ['red'], isSpecial: false },
        { cardName: '8', cardColor: ['red'], isSpecial: false },
        { cardName: '9', cardColor: ['red'], isSpecial: false },
        { cardName: '1', cardColor: ['blue'], isSpecial: false },
        { cardName: '+2', cardColor: ['blue'], isSpecial: true },
        { cardName: '3', cardColor: ['blue'], isSpecial: false },
        { cardName: '4', cardColor: ['blue'], isSpecial: false },
        { cardName: '5', cardColor: ['blue'], isSpecial: false },
        { cardName: '6', cardColor: ['blue'], isSpecial: false },
        { cardName: '7', cardColor: ['blue'], isSpecial: false },
        { cardName: '8', cardColor: ['blue'], isSpecial: false },
        { cardName: '9', cardColor: ['blue'], isSpecial: false },
        { cardName: 'plus', cardColor: ['green'], isSpecial: true },
        { cardName: 'plus', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'plus', cardColor: ['red'], isSpecial: true },
        { cardName: 'plus', cardColor: ['blue'], isSpecial: true },
        { cardName: 'taki', cardColor: ['green'], isSpecial: true },
        { cardName: 'taki', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'taki', cardColor: ['red'], isSpecial: true },
        { cardName: 'taki', cardColor: ['blue'], isSpecial: true },
        { cardName: 'stop', cardColor: ['green'], isSpecial: true },
        { cardName: 'stop', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'stop', cardColor: ['red'], isSpecial: true },
        { cardName: 'stop', cardColor: ['blue'], isSpecial: true },
        { cardName: 'revert', cardColor: ['green'], isSpecial: true },
        { cardName: 'revert', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'revert', cardColor: ['red'], isSpecial: true },
        { cardName: 'revert', cardColor: ['blue'], isSpecial: true },
        { cardName: 'king', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'superTaki', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: '1', cardColor: ['green'], isSpecial: false },
        { cardName: '+2', cardColor: ['green'], isSpecial: true },
        { cardName: '3', cardColor: ['green'], isSpecial: false },
        { cardName: '4', cardColor: ['green'], isSpecial: false },
        { cardName: '5', cardColor: ['green'], isSpecial: false },
        { cardName: '6', cardColor: ['green'], isSpecial: false },
        { cardName: '7', cardColor: ['green'], isSpecial: false },
        { cardName: '8', cardColor: ['green'], isSpecial: false },
        { cardName: '9', cardColor: ['green'], isSpecial: false },
        { cardName: '1', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2', cardColor: ['yellow'], isSpecial: true },
        { cardName: '3', cardColor: ['yellow'], isSpecial: false },
        { cardName: '4', cardColor: ['yellow'], isSpecial: false },
        { cardName: '5', cardColor: ['yellow'], isSpecial: false },
        { cardName: '6', cardColor: ['yellow'], isSpecial: false },
        { cardName: '7', cardColor: ['yellow'], isSpecial: false },
        { cardName: '8', cardColor: ['yellow'], isSpecial: false },
        { cardName: '9', cardColor: ['yellow'], isSpecial: false },
        { cardName: '1', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2', cardColor: ['red'], isSpecial: true },
        { cardName: '3', cardColor: ['red'], isSpecial: false },
        { cardName: '4', cardColor: ['red'], isSpecial: false },
        { cardName: '5', cardColor: ['red'], isSpecial: false },
        { cardName: '6', cardColor: ['red'], isSpecial: false },
        { cardName: '7', cardColor: ['red'], isSpecial: false },
        { cardName: '8', cardColor: ['red'], isSpecial: false },
        { cardName: '9', cardColor: ['red'], isSpecial: false },
        { cardName: '1', cardColor: ['blue'], isSpecial: false },
        { cardName: '+2', cardColor: ['blue'], isSpecial: true },
        { cardName: '3', cardColor: ['blue'], isSpecial: false },
        { cardName: '4', cardColor: ['blue'], isSpecial: false },
        { cardName: '5', cardColor: ['blue'], isSpecial: false },
        { cardName: '6', cardColor: ['blue'], isSpecial: false },
        { cardName: '7', cardColor: ['blue'], isSpecial: false },
        { cardName: '8', cardColor: ['blue'], isSpecial: false },
        { cardName: '9', cardColor: ['blue'], isSpecial: false },
        { cardName: 'plus', cardColor: ['green'], isSpecial: true },
        { cardName: 'plus', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'plus', cardColor: ['red'], isSpecial: true },
        { cardName: 'plus', cardColor: ['blue'], isSpecial: true },
        { cardName: 'taki', cardColor: ['green'], isSpecial: true },
        { cardName: 'taki', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'taki', cardColor: ['red'], isSpecial: true },
        { cardName: 'taki', cardColor: ['blue'], isSpecial: true },
        { cardName: 'stop', cardColor: ['green'], isSpecial: true },
        { cardName: 'stop', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'stop', cardColor: ['red'], isSpecial: true },
        { cardName: 'stop', cardColor: ['blue'], isSpecial: true },
        { cardName: 'revert', cardColor: ['green'], isSpecial: true },
        { cardName: 'revert', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'revert', cardColor: ['red'], isSpecial: true },
        { cardName: 'revert', cardColor: ['blue'], isSpecial: true },
        { cardName: 'king', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'superTaki', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
    ]
    return cards
}