export const cardDeckService = {
    cardDeck
}

function cardDeck(){
    const cards = [
        { cardName: '1 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '+2 green a', cardColor: ['green'], isSpecial: true },
        { cardName: '3 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '4 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '5 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '6 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '7 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '8 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '9 green a', cardColor: ['green'], isSpecial: false },
        { cardName: '1 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2 yellow a', cardColor: ['yellow'], isSpecial: true },
        { cardName: '3 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '4 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '5 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '6 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '7 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '8 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '9 yellow a', cardColor: ['yellow'], isSpecial: false },
        { cardName: '1 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '+2 red a', cardColor: ['red'], isSpecial: true },
        { cardName: '3 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '4 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '5 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '6 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '7 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '8 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '9 red a', cardColor: ['red'], isSpecial: false },
        { cardName: '1 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '+2 blue a', cardColor: ['blue'], isSpecial: true },
        { cardName: '3 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '4 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '5 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '6 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '7 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '8 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: '9 blue a', cardColor: ['blue'], isSpecial: false },
        { cardName: 'plus green a', cardColor: ['green'], isSpecial: true },
        { cardName: 'plus yellow a', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'plus red a', cardColor: ['red'], isSpecial: true },
        { cardName: 'plus blue a', cardColor: ['blue'], isSpecial: true },
        { cardName: 'taki green a', cardColor: ['green'], isSpecial: true },
        { cardName: 'taki yellow a', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'taki red a', cardColor: ['red'], isSpecial: true },
        { cardName: 'taki blue a', cardColor: ['blue'], isSpecial: true },
        { cardName: 'stop green a', cardColor: ['green'], isSpecial: true },
        { cardName: 'stop yellow a', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'stop red a', cardColor: ['red'], isSpecial: true },
        { cardName: 'stop blue a', cardColor: ['blue'], isSpecial: true },
        { cardName: 'revert green a', cardColor: ['green'], isSpecial: true },
        { cardName: 'revert yellow a', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'revert red a', cardColor: ['red'], isSpecial: true },
        { cardName: 'revert blue a', cardColor: ['blue'], isSpecial: true },
        { cardName: 'king a', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor a', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor b', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'superTaki a', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: '1 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '+2 green b', cardColor: ['green'], isSpecial: true },
        { cardName: '3 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '4 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '5 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '6 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '7 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '8 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '9 green b', cardColor: ['green'], isSpecial: false },
        { cardName: '1 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '+2 yellow b', cardColor: ['yellow'], isSpecial: true },
        { cardName: '3 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '4 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '5 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '6 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '7 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '8 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '9 yellow b', cardColor: ['yellow'], isSpecial: false },
        { cardName: '1 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '+2 red b', cardColor: ['red'], isSpecial: true },
        { cardName: '3 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '4 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '5 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '6 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '7 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '8 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '9 red b', cardColor: ['red'], isSpecial: false },
        { cardName: '1 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '+2 blue b', cardColor: ['blue'], isSpecial: true },
        { cardName: '3 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '4 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '5 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '6 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '7 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '8 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: '9 blue b', cardColor: ['blue'], isSpecial: false },
        { cardName: 'plus green b', cardColor: ['green'], isSpecial: true },
        { cardName: 'plus yellow b', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'plus red b', cardColor: ['red'], isSpecial: true },
        { cardName: 'plus blue b', cardColor: ['blue'], isSpecial: true },
        { cardName: 'taki green b', cardColor: ['green'], isSpecial: true },
        { cardName: 'taki yellow b', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'taki red b', cardColor: ['red'], isSpecial: true },
        { cardName: 'taki blue b', cardColor: ['blue'], isSpecial: true },
        { cardName: 'stop green b', cardColor: ['green'], isSpecial: true },
        { cardName: 'stop yellow b', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'stop red b', cardColor: ['red'], isSpecial: true },
        { cardName: 'stop blue b', cardColor: ['blue'], isSpecial: true },
        { cardName: 'revert green b', cardColor: ['green'], isSpecial: true },
        { cardName: 'revert yellow b', cardColor: ['yellow'], isSpecial: true },
        { cardName: 'revert red b', cardColor: ['red'], isSpecial: true },
        { cardName: 'revert blue b', cardColor: ['blue'], isSpecial: true },
        { cardName: 'king b', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor c', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'changeColor d', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
        { cardName: 'superTaki b', cardColor: ['green', 'yellow', 'red', 'blue'], isSpecial: true },
    ]
    return cards
}